version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1-node-browsers
      # Environment variable for all commands executed in the primary container
        environment:
          RAILS_ENV: test
          RAKE_ENV: test
          PGUSER: postgres

      - image: circleci/postgres:9.6.3-alpine

    working_directory: ~/alexkval-twitter

    parallelism: 4

    steps:
      - checkout

      - run:
          name: "Checking Node.js Versions"
          command: |
            node --version
            npm --version

      # install 'psql' for db:structure:load
      - run: sudo apt install postgresql-client

      # Download and cache dependencies
      - restore_cache:
          key: altw-bundler-v1-{{ .Branch }}-{{ checksum "Gemfile.lock" }}

      - restore_cache:
          key: altw-npm-v1-{{ .Branch }}-{{ checksum "package.json" }}

      - run:
          name: install node packages
          command: npm install

      - run:
          name: install bundler dependencies
          command: |
            bundle install --without development \
                          --without production \
                          --deployment \
                          --jobs=4 \
                          --retry=3

      - save_cache:
          name: Save ruby gems cache
          key: altw-bundler-v1-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            # the --deployment flag tells bundler to install here
            - vendor/bundle

      - save_cache:
          name: Save node packages cache
          key: altw-npm-v1-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      - run:
          name: Set up database
          command: bundle exec rake db:create db:structure:load

      # run tests!
      - run:
          name: run RSpec
          command: bundle exec rspec

      - run:
          name: run Microtests
          command: bundle exec rake test
